import asianPaintsLogo from '../public/asian-paints.svg';
import bergerPaintsLogo from '../public/berger-paints.png';
import drFixitLogo from '../public/dr-fixit.svg';
export const topCategories = ["All Categories", "Home Paint", "Industrial"];

export const subCategories: Record<string, string[]> = {
  "Home Paint": [
    "All Home Paint",
    "Interior Wall",
    "Exterior Wall",
    "Primer",
    "Waterproofing",
    "Wood Finishes",
    "Metals and Grills",
  ],
  Industrial: [
    "All Industrial",
    "PU Coatings",
    "Epoxy Coatings",
    "Food Grade Epoxy",
    "Synthetic Enamels",
    "MIOs",
    "Floor Epoxy Coatings",
  ],
};

export const brands = [
  "All Brands",
  "Asian Paints",
  "Berger Paints",
  "Dr. Fixit",
  "MRF Vapocure",
];

export interface BrandDetail {
  name: string;
  logo: string;
  description: string;
  tags: string[];
  isAuthorised: boolean;
}

export const brandDetails: BrandDetail[] = [
  {
    name: "Asian Paints",
    logo: asianPaintsLogo,
    description: "India's #1 paint brand — Royale luxury emulsions, Apex exterior & Teflon technology trusted by millions of homes.",
    tags: ["Interior", "Exterior", "Primer"],
    isAuthorised: true
  },
  {
    name: "Berger Paints",
    logo: bergerPaintsLogo,
    description: "Premium Silk luxury emulsions & WeatherCoat exterior series. Value leader in India's premium paint segment.",
    tags: ["Silk Range", "Weathercoat", "Distemper"],
    isAuthorised: true
  },
  {
    name: "Dr. Fixit",
    logo: drFixitLogo,
    description: "The trusted name in structural waterproofing and construction chemicals for permanent protection against water damage.",
    tags: ["Waterproofing", "Roofseal", "Bathseal"],
    isAuthorised: true
  },
  {
    name: "MRF Vapocure",
    logo: "https://www.mrfpaint.com/wp-content/uploads/2024/11/mrf-logo-1.png",
    description: "Engineering-grade paints by MRF. Shyne luxury emulsion & Weathercoat acrylic for outstanding durability.",
    tags: ["Shyne", "Weathercoat", "Enamel"],
    isAuthorised: true
  }
];

export const mockProducts = [
  {
    id: 1,
    name: "Apex Ultima Protek Duralife",
    brand: "Asian Paints",
    topCategory: "Home Paint",
    subCategory: "Exterior Wall",
    price: "₹ 928.00",
    properties: [
      "WALLS of S.T.E.E.L",
      "Advanced PUD Formula",
      "15 years warranty*",
    ],
    popular: true,
    image:
      "https://www.asianpaints.com/content/dam/asian_paints/textures/others/duralife_topcoat_single-layer.png",
  },
  {
    id: 2,
    name: "Silk Glamor Luxury Emulsion",
    brand: "Berger Paints",
    topCategory: "Home Paint",
    subCategory: "Interior Wall",
    price: "₹ 850.00",
    properties: ["Ultra Glamorous Sheen", "High Stain Resistance", "Over 10,000+ shades"],
    popular: true,
    image: "https://www.bergerpaints.com/products/packshots/silk-glamor.png",
  },
  {
    id: 3,
    name: "Apex Ultima Protek",
    brand: "Asian Paints",
    topCategory: "Home Paint",
    subCategory: "Exterior Wall",
    price: "₹ 692.00",
    properties: [
      "Home Lamination powered by Graphene",
      "Elastomeric Armour",
      "12 years Warranty*",
    ],
    popular: true,
    image:
      "https://www.asianpaints.com/content/dam/asian_paints/products/packshots/exterior-walls-ultima-protek-topcoat-new-asian-paints.png",
  },
  {
    id: 4,
    name: "WeatherCoat Long Life",
    brand: "Berger Paints",
    topCategory: "Home Paint",
    subCategory: "Exterior Wall",
    price: "₹ 720.00",
    properties: ["Silicon Technology", "Dust Guard", "10 Years Performance Warranty"],
    popular: true,
    image: "https://www.bergerpaints.com/products/packshots/weathercoat-long-life.png",
  },
  {
    id: 5,
    name: "Royale Glitz",
    brand: "Asian Paints",
    topCategory: "Home Paint",
    subCategory: "Interior Wall",
    price: "₹ 892.00",
    properties: [
      "Perfect Crème Finish in Ultra Sheen",
      "Teflon Surface Protector",
      "8 Years Warranty"
    ],
    popular: true,
    image:
      "https://www.asianpaints.com/content/dam/asian_paints/products/packshots/royale-glitz-new-packshot.png",
  },
  {
    id: 6,
    name: "Royale Luxury Emulsion",
    brand: "Asian Paints",
    topCategory: "Home Paint",
    subCategory: "Interior Wall",
    price: "₹ 780.00",
    properties: [
      "Smooth Exquisite Soft Sheen",
      "Excellent Stain Resistance (Teflon™)",
      "Anti-Bacterial & Low VOC (Eco-Friendly)",
      "High Scrub Resistance & Highly Washable",
      "5 Years Performance Warranty*"
    ],
    popular: true,
    image: "https://www.asianpaints.com/content/dam/asian_paints/products/packshots/royale-luxury-emulsion-new-packshot.png",
  },
  {
    id: 7,
    name: "Apcolite Premium Emulsion",
    brand: "Asian Paints",
    topCategory: "Home Paint",
    subCategory: "Interior Wall",
    price: "₹ 450.00",
    properties: [
      "Rich Flat Matt Finish",
      "Advanced Fungus & Mildew Shield",
      "Highly Washable (Resists Everyday Stains)",
      "Over 1600+ Gorgeous Shades",
      "5 Years Performance Warranty*"
    ],
    popular: true,
    image:
      "https://www.asianpaints.com/content/dam/asian_paints/products/packshots/apcolite-premium-emulsion-new-packshot.png",
  },
  {
    id: 50,
    name: "Royale Aspira",
    brand: "Asian Paints",
    topCategory: "Home Paint",
    subCategory: "Interior Wall",
    price: "₹ 1011.00",
    properties: [
      "Water Beading Technology",
      "Luxury with Teflon™",
      "8 Years Warranty"
    ],
    popular: true,
    image: "https://www.asianpaints.com/content/dam/asian_paints/products/packshots/royale-aspira-new-packshot.png",
  },
  {
    id: 51,
    name: "Royale Shyne Luxury Emulsion",
    brand: "Asian Paints",
    topCategory: "Home Paint",
    subCategory: "Interior Wall",
    price: "₹ 850.00",
    properties: [
      "High Intensity Lustre Sheen",
      "Excellent Stain Resistance with Teflon™",
      "Clean Air & Ultra-Low VOC",
      "Superb Scrub Resistance (Easy Cleaning)",
      "6 Years Performance Warranty*"
    ],
    popular: true,
    image: "https://www.asianpaints.com/content/dam/asian_paints/products/packshots/royale-shyne-new-packshot.png",
  },
  {
    id: 52,
    name: "Royale Matt Emulsion",
    brand: "Asian Paints",
    topCategory: "Home Paint",
    subCategory: "Interior Wall",
    price: "₹ 820.00",
    properties: [
      "Pure Architectural Flat Matt Finish",
      "Excellent Light Diffusion (Hides Wall Flaws)",
      "Super Stain Resistance (Teflon™)",
      "High Washability & Smooth Feel",
      "5 Years Performance Warranty*"
    ],
    popular: false,
    image: "https://www.asianpaints.com/content/dam/asian_paints/products/packshots/royale-matt-luxury-emulsion-packshot.png",
  },
  {
    id: 53,
    name: "Royale Health Shield",
    brand: "Asian Paints",
    topCategory: "Home Paint",
    subCategory: "Interior Wall",
    price: "₹ 1,120.00",
    properties: [
      "Kills 99.9% Bacteria & Virus (Silver Ion)",
      "Neutralizes Formaldehyde (Purifies Indoor Air)",
      "Exquisite Soft Sheen Surface",
      "Highly Washable & Asthma Friendly approved",
      "5 Years Performance Warranty*"
    ],
    popular: true,
    image: "https://www.asianpaints.com/content/dam/asian_paints/products/packshots/royale-health-shield-new-packshot.png",
  },
  {
    id: 54,
    name: "Apcolite Premium Satin Emulsion",
    brand: "Asian Paints",
    topCategory: "Home Paint",
    subCategory: "Interior Wall",
    price: "₹ 510.00",
    properties: [
      "Satin Luster Gloss Glow",
      "Stain Guard Wall Technology",
      "High Wet Scrub Resistance",
      "Anti-Fungal & Anti-Algal Formula",
      "5 Years Performance Warranty*"
    ],
    popular: false,
    image: "https://www.asianpaints.com/content/dam/asian_paints/products/packshots/apcolite-premium-satin-emulsion-new-packshot.png",
  },
  {
    id: 55,
    name: "Apcolite Advanced Emulsion",
    brand: "Asian Paints",
    topCategory: "Home Paint",
    subCategory: "Interior Wall",
    price: "₹ 480.00",
    properties: [
      "Advanced Stain Guard (Easy Wipe)",
      "Rich Matt Texture and Finish",
      "Superior Opacity and Sheet Coverage",
      "Exceptional Washability & Long Lasting",
      "5 Years Performance Warranty*"
    ],
    popular: false,
    image: "https://www.asianpaints.com/content/dam/asian_paints/products/packshots/apcolite-advanced-emulsion-packshot.png",
  },
  {
    id: 8,
    name: "Silk Breathe Free",
    brand: "Berger Paints",
    topCategory: "Home Paint",
    subCategory: "Interior Wall",
    price: "₹ 950.00",
    properties: ["Anti-Bacterial", "Air Purifying", "High Sheen"],
    popular: false,
    image: "https://www.bergerpaints.com/products/packshots/silk-breathe-free.png",
  },
  {
    id: 9,
    name: "Easy Clean Fresh",
    brand: "Berger Paints",
    topCategory: "Home Paint",
    subCategory: "Interior Wall",
    price: "₹ 520.00",
    properties: ["Cross-Link Polymers", "Stain Resistant", "Fresh Fragrance"],
    popular: true,
    image: "https://www.bergerpaints.com/products/packshots/easy-clean.png",
  },
  {
    id: 10,
    name: "LW+ Waterproofing",
    brand: "Dr. Fixit",
    topCategory: "Home Paint",
    subCategory: "Waterproofing",
    price: "₹ 165.00",
    properties: ["Integral Liquid Waterproofing", "Prevents Corrosion", "Better Workability"],
    popular: true,
    image: "https://www.drfixit.co.in/content/dam/drfixit/packshots/lw-plus.png",
  },
  {
    id: 11,
    name: "URP 301",
    brand: "Dr. Fixit",
    topCategory: "Home Paint",
    subCategory: "Waterproofing",
    price: "₹ 440.00",
    properties: ["SBR Latex", "High Bonding Strength", "Structural Repair"],
    popular: true,
    image: "https://www.drfixit.co.in/content/dam/drfixit/packshots/pidiproof-urp.png",
  },
  {
    id: 12,
    name: "Raincoat",
    brand: "Dr. Fixit",
    topCategory: "Home Paint",
    subCategory: "Waterproofing",
    price: "₹ 550.00",
    properties: ["Exterior Waterproof coating", "Elastomeric", "Crack Bridging"],
    popular: true,
    image: "https://www.drfixit.co.in/content/dam/drfixit/packshots/raincoat.png",
  },
  {
    id: 13,
    name: "Zinkrom-S Primer",
    brand: "MRF Vapocure",
    topCategory: "Industrial",
    subCategory: "PU Coatings",
    price: "₹ 620.00",
    properties: ["Anti-Corrosive", "High Performance", "Quick Drying"],
    popular: true,
    image: "https://www.mrfpaint.com/wp-content/uploads/2024/11/zinkrom-s.png",
  },
  {
    id: 14,
    name: "Nilaya Arc Matt",
    brand: "Asian Paints",
    topCategory: "Home Paint",
    subCategory: "Interior Wall",
    price: "₹ 1,050.00",
    properties: [
      "Lime-Based Finish",
      "Artisanal Matt Finish",
      "10 Years Warranty",
    ],
    popular: true,
    image:
      "https://www.asianpaints.com/content/dam/asian_paints/products/packshots/Nilaya-Arc-Matt-new.png",
  },
  {
    id: 60,
    name: "Nilaya Arc Pearlescent",
    brand: "Asian Paints",
    topCategory: "Home Paint",
    subCategory: "Interior Wall",
    price: "₹ 1,200.00",
    properties: [
      "Lime-Based Finish",
      "Alluring Pearl Finish",
      "10 Years Warranty",
    ],
    popular: true,
    image:
      "https://www.asianpaints.com/content/dam/asian_paints/products/packshots/Nilaya-Arc-Pearlescent-new.png",
  },
  {
    id: 15,
    name: "Zinc Rich Primer",
    brand: "MRF Vapocure",
    topCategory: "Industrial",
    subCategory: "Epoxy Coatings",
    price: "₹ 850.00",
    properties: ["Cold Galvanizing", "Superior Protection", "Heavy Duty"],
    popular: true,
    image: "https://www.mrfpaint.com/wp-content/uploads/2024/11/zinc-rich.png",
  },
  {
    id: 16,
    name: "Epoxy Grey Primer",
    brand: "MRF Vapocure",
    topCategory: "Industrial",
    subCategory: "Epoxy Coatings",
    price: "₹ 580.00",
    properties: ["Excellent Adhesion", "Chemical Resistance", "Industrial Grade"],
    popular: false,
    image: "https://www.mrfpaint.com/wp-content/uploads/2024/11/epoxy-grey.png",
  },
  {
    id: 17,
    name: "Apex Dust Proof",
    brand: "Asian Paints",
    topCategory: "Home Paint",
    subCategory: "Exterior Wall",
    price: "₹ 426.00",
    properties: [
      "Nano Block",
      "Dust Proof Technology",
      "6-years Warranty*",
    ],
    popular: true,
    image:
      "https://www.asianpaints.com/content/dam/asian_paints/products/packshots/exterior-walls-apex-dust-proof-emulsion-packshot-asian-paints.png",
  },
  {
    id: 18,
    name: "Vapocure Thinner",
    brand: "MRF Vapocure",
    topCategory: "Industrial",
    subCategory: "PU Coatings",
    price: "₹ 320.00",
    properties: ["high Purity", "Fast Evaporation", "Excellent Leveling"],
    popular: false,
    image: "https://www.mrfpaint.com/wp-content/uploads/2024/11/thinner.png",
  },
  {
    id: 19,
    name: "WeatherCoat Anti Dust",
    brand: "Berger Paints",
    topCategory: "Home Paint",
    subCategory: "Exterior Wall",
    price: "₹ 480.00",
    properties: ["Dust Repellent", "Anti-Fungal", "Matte Finish"],
    popular: true,
    image: "https://www.bergerpaints.com/products/packshots/weathercoat-anti-dust.png",
  },
  {
    id: 20,
    name: "MIO Coatings",
    brand: "MRF Vapocure",
    topCategory: "Industrial",
    subCategory: "MIOs",
    price: "₹ 740.00",
    properties: ["Micaceous Iron Oxide", "Barrier Protection", "Extreme Durability"],
    popular: true,
    image: "https://www.mrfpaint.com/wp-content/uploads/2024/11/mio.png",
  },
  {
    id: 21,
    name: "RUCA Luxury Emulsion",
    brand: "MRF Vapocure",
    topCategory: "Home Paint",
    subCategory: "Interior Wall",
    price: "₹ 1,150.00",
    properties: ["Luxury Finish", "High Washability", "Stain Resistant", "10 Years Warranty*"],
    popular: true,
    image:
      "https://www.mrfpaint.com/wp-content/uploads/2024/11/ruca-copy.png",
  },
  {
    id: 22,
    name: "Bison Interior Emulsion",
    brand: "Berger Paints",
    topCategory: "Home Paint",
    subCategory: "Interior Wall",
    price: "₹ 280.00",
    properties: ["Value for Money", "Matt Finish", "Wide Range of Colors"],
    popular: false,
    image: "https://www.bergerpaints.com/products/packshots/bison-interior.png",
  },
  {
    id: 23,
    name: "WeatherCoat Glow",
    brand: "Berger Paints",
    topCategory: "Home Paint",
    subCategory: "Exterior Wall",
    price: "₹ 380.00",
    properties: ["Stay Clean", "Reflective Sheen", "Anti-Algal"],
    popular: false,
    image: "https://www.bergerpaints.com/products/packshots/weathercoat-glow.png",
  },
  {
    id: 24,
    name: "Fast Dry PU Polish",
    brand: "MRF Vapocure",
    topCategory: "Home Paint",
    subCategory: "Wood Finishes",
    price: "₹ 820.00",
    properties: ["High Gloss", "Quick Drying", "Excellent Clarity"],
    popular: true,
    image: "https://www.mrfpaint.com/wp-content/uploads/2024/11/wood-finish.png",
  },
  {
    id: 25,
    name: "Solarex Heat Reflective",
    brand: "Berger Paints",
    topCategory: "Home Paint",
    subCategory: "Exterior Wall",
    price: "₹ 1,100.00",
    properties: ["SRI Certified", "Reduces Temp", "UV Resistant"],
    popular: true,
    image: "https://www.bergerpaints.com/products/packshots/solarex.png",
  },
  {
    id: 26,
    name: "Visa Emulsion",
    brand: "MRF Vapocure",
    topCategory: "Home Paint",
    subCategory: "Interior Wall",
    price: "₹ 290.00",
    properties: ["Value for Money", "Matt Finish", "Good Opacity", "4 Years Warranty*"],
    popular: true,
    image:
      "https://www.mrfpaint.com/wp-content/uploads/2024/10/Untitled-design-16.png",
  },
  {
    id: 27,
    name: "AquaFresh PU Exterior",
    brand: "MRF Vapocure",
    topCategory: "Home Paint",
    subCategory: "Exterior Wall",
    price: "₹ 1,050.00",
    properties: ["Weather Resistant", "PU Exterior Finish", "Anti-Fungal", "8 Years Warranty*"],
    popular: true,
    image:
      "https://www.mrfpaint.com/wp-content/uploads/2024/11/Untitled-design-19.png",
  },
  {
    id: 28,
    name: "Apex Advanced",
    brand: "Asian Paints",
    topCategory: "Home Paint",
    subCategory: "Exterior Wall",
    price: "₹ 380.00",
    properties: ["Anti-Algal", "Good Weather Resistance", "5 Years Warranty"],
    popular: false,
    image: "https://www.asianpaints.com/content/dam/asian_paints/products/packshots/exterior-walls-apex-advanced-weatherproof-emulsion-packshot-asian-paints.png",
  },
  {
    id: 29,
    name: "Tractor Emulsion",
    brand: "Asian Paints",
    topCategory: "Home Paint",
    subCategory: "Interior Wall",
    price: "₹ 210.00",
    properties: [
      "Smart Choice Economy Matt",
      "1.5x More Coverage than Distempers",
      "Smooth Elegant Leveling Surface",
      "Washable & Easy to Maintain",
      "Value For Money Smart Upgrade"
    ],
    popular: true,
    image: "https://www.asianpaints.com/content/dam/asian_paints/products/packshots/tractor-emulsion-new-packshot.png",
  },
  {
    id: 56,
    name: "Tractor Sparc Emulsion",
    brand: "Asian Paints",
    topCategory: "Home Paint",
    subCategory: "Interior Wall",
    price: "₹ 180.00",
    properties: [
      "Highly Economical Smooth Matt",
      "Direct Distemper Upgrade Choice",
      "Fungus Resistant Formulation",
      "Smooth Seamless Interior Wall Coat",
      "Smartest Entry-level Emulsion"
    ],
    popular: false,
    image: "https://www.asianpaints.com/content/dam/asian_paints/products/packshots/tractor-sparc-emulsion-packshot.png",
  },
  {
    id: 57,
    name: "Tractor Emulsion Shyne",
    brand: "Asian Paints",
    topCategory: "Home Paint",
    subCategory: "Interior Wall",
    price: "₹ 240.00",
    properties: [
      "Economical High Sheen Glow",
      "Excellent Segment Coverage & Finish",
      "Brilliant Reflective Paint Sheen",
      "Wipeable Light Wash Care",
      "Value Sheen Choice in Budget"
    ],
    popular: true,
    image: "https://www.asianpaints.com/content/dam/asian_paints/products/packshots/tractor-emulsion-shyne-packshot.png",
  },
  {
    id: 58,
    name: "Tractor Uno Acrylic Distemper",
    brand: "Asian Paints",
    topCategory: "Home Paint",
    subCategory: "Interior Wall",
    price: "₹ 120.00",
    properties: [
      "Economical Classic Distemper",
      "Water-Based Breathable Smooth Matt",
      "Direct Over-Plaster Wall Coater",
      "Easy Application and Rapid Dry"
    ],
    popular: false,
    image: "https://www.asianpaints.com/content/dam/asian_paints/products/packshots/tractor-uno-acrylic-distemper-packshot.png",
  },
  {
    id: 30,
    name: "Ace Exterior Emulsion",
    brand: "Asian Paints",
    topCategory: "Home Paint",
    subCategory: "Exterior Wall",
    price: "₹ 240.00",
    properties: ["Anti-Algal Performance", "Economy Exterior", "Water Resistance"],
    popular: false,
    image: "https://www.asianpaints.com/content/dam/asian_paints/products/packshots/exterior-walls-ace-exterior-emulsion-packshot-asian-paints.png",
  },
  {
    id: 31,
    name: "Luxol High Gloss Enamel",
    brand: "Berger Paints",
    topCategory: "Home Paint",
    subCategory: "Metals and Grills",
    price: "₹ 340.00",
    properties: ["High Gloss", "Tough Film", "Anti-Corrosive"],
    popular: true,
    image: "https://www.bergerpaints.com/products/packshots/luxol.png",
  },
  {
    id: 32,
    name: "WoodCoat Exterior",
    brand: "MRF Vapocure",
    topCategory: "Home Paint",
    subCategory: "Wood Finishes",
    price: "₹ 1,180.00",
    properties: ["Exterior Polish", "UV Resistance", "Gloss & Matt"],
    popular: true,
    image:
      "https://www.mrfpaint.com/wp-content/uploads/2024/11/woodcoat-Ext-copy.png",
  },
  {
    id: 33,
    name: "Bathseal Waterproofing",
    brand: "Dr. Fixit",
    topCategory: "Home Paint",
    subCategory: "Waterproofing",
    price: "₹ 480.00",
    properties: ["Bathroom Waterproofing", "Ready to use", "High Durability"],
    popular: false,
    image: "https://www.drfixit.co.in/content/dam/drfixit/packshots/bathseal.png",
  },
  {
    id: 34,
    name: "Floor Epoxy Coating",
    brand: "MRF Vapocure",
    topCategory: "Industrial",
    subCategory: "Floor Epoxy Coatings",
    price: "₹ 980.00",
    properties: ["Heavy Traffic Resistance", "Chemical Resistant", "Seamless Finish"],
    popular: true,
    image: "https://www.mrfpaint.com/wp-content/uploads/2024/11/floor-epoxy.png",
  },
  {
    id: 35,
    name: "PU Luxury Finish",
    brand: "MRF Vapocure",
    topCategory: "Home Paint",
    subCategory: "Interior Wall",
    price: "₹ 1,450.00",
    properties: ["PU Luxury", "Ultimate Sheen", "High Durability"],
    popular: true,
    image: "https://www.mrfpaint.com/wp-content/uploads/2024/11/pu-luxury.png",
  },
  {
    id: 36,
    name: "Newcoat Waterproofing",
    brand: "Dr. Fixit",
    topCategory: "Home Paint",
    subCategory: "Waterproofing",
    price: "₹ 620.00",
    properties: ["Terrace Waterproofing", "Fiber Reinforced", "Heat Reflective"],
    popular: true,
    image: "https://www.drfixit.co.in/content/dam/drfixit/packshots/newcoat.png",
  },
  {
    id: 37,
    name: "Decoprime Wall Primer",
    brand: "Asian Paints",
    topCategory: "Home Paint",
    subCategory: "Primer",
    price: "₹ 180.00",
    properties: ["Undercoat for Walls", "Excellent Opacity", "Strong Grip"],
    popular: false,
    image: "https://www.asianpaints.com/content/dam/asian_paints/products/packshots/decoprime-wall-primer-new-packshot.png",
  },
  {
    id: 38,
    name: "Emporio PU Polish",
    brand: "Asian Paints",
    topCategory: "Home Paint",
    subCategory: "Wood Finishes",
    price: "₹ 1,350.00",
    properties: ["Premium Italian Wood Finish", "Mirror Like Gloss", "Excellent Scratch Resistance"],
    popular: true,
    image: "https://www.asianpaints.com/content/dam/asian_paints/products/packshots/wood-finishes-italiano-emporio-pu-packshot-asian-paints.png",
  },
  {
    id: 39,
    name: "Apcolite Premium Enamel",
    brand: "Asian Paints",
    topCategory: "Home Paint",
    subCategory: "Metals and Grills",
    price: "₹ 290.00",
    properties: ["High Gloss Finish", "Stain Resistance", "Tough Film"],
    popular: false,
    image: "https://www.asianpaints.com/content/dam/asian_paints/products/packshots/apcolite-premium-enamel-hi-gloss-new-packshot.png",
  },
  {
    id: 40,
    name: "Specta PU Enamel",
    brand: "MRF Vapocure",
    topCategory: "Home Paint",
    subCategory: "Metals and Grills",
    price: "₹ 360.00",
    properties: ["PU Enamel", "Excellent Leveling", "High Coverage"],
    popular: true,
    image:
      "https://www.mrfpaint.com/wp-content/uploads/2024/10/specta-copy.png",
  },
  {
    id: 41,
    name: "AquaFresh DampGarde",
    brand: "MRF Vapocure",
    topCategory: "Home Paint",
    subCategory: "Primer",
    price: "₹ 450.00",
    properties: ["Waterproofing Primer", "Excellent Adhesion", "Anti-Efflorescence"],
    popular: true,
    image: "https://www.mrfpaint.com/wp-content/uploads/2024/11/dampgarde-copy.png",
  },
  {
    id: 42,
    name: "Food Grade Epoxy",
    brand: "MRF Vapocure",
    topCategory: "Industrial",
    subCategory: "Food Grade Epoxy",
    price: "₹ 1,250.00",
    properties: ["Non-Toxic", "Water Tank Safe", "Excellent Chemical Resistance"],
    popular: true,
    image: "https://www.mrfpaint.com/wp-content/uploads/2024/11/food-grade.png",
  },
  {
    id: 43,
    name: "Synthetic Enamel Grey",
    brand: "MRF Vapocure",
    topCategory: "Industrial",
    subCategory: "Synthetic Enamels",
    price: "₹ 310.00",
    properties: ["High Gloss", "Excellent Durability", "Industrial Air Drying"],
    popular: false,
    image: "https://www.mrfpaint.com/wp-content/uploads/2024/11/enamel.png",
  },
];
